import React from 'react';

const TermsOfService: React.FC = () => {
  return (
    <>
      <title>Terms of Service - Telugu AI Voice Chat</title>
      <meta name="description" content="Please read our Terms of Service carefully before using the Telugu AI Voice Chat application. This page outlines the rules and guidelines for our service." />
    <div className="min-h-screen bg-gradient-to-br from-indigo-900 via-purple-800 to-pink-700 text-white p-4 sm:p-8">
      <div className="max-w-4xl mx-auto bg-black/30 backdrop-blur-xl rounded-2xl shadow-2xl p-6 sm:p-10">
        <h1 className="text-4xl sm:text-5xl font-black mb-8 text-center animate-gradient">Terms of Service</h1>
        
        <div className="space-y-6 text-indigo-100 text-left text-base sm:text-lg">
          <p><strong className="text-white">Last Updated:</strong> {new Date().toLocaleDateString()}</p>

          <p>Please read these Terms of Service ("Terms") carefully before using the Telugu AI Voice Chat website (the "Service") operated by us. Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms. These Terms apply to all visitors, users, and others who access or use the Service.</p>

          <h2 className="text-2xl sm:text-3xl font-bold text-pink-300 pt-4 pb-2">1. Acceptance of Terms</h2>
          <p>By accessing or using the Service, you agree to be bound by these Terms. If you disagree with any part of the terms, then you may not access the Service.</p>

          <h2 className="text-2xl sm:text-3xl font-bold text-pink-300 pt-4 pb-2">2. Description of Service</h2>
          <p>Our Service provides an interactive AI-powered voice chat experience in the Telugu language. The responses are generated by an artificial intelligence model and are for informational and entertainment purposes only. We do not guarantee the accuracy, completeness, or usefulness of any information provided.</p>

          <h2 className="text-2xl sm:text-3xl font-bold text-pink-300 pt-4 pb-2">3. User Conduct</h2>
          <p>You agree not to use the Service to:</p>
          <ul className="list-disc list-inside pl-4 space-y-2">
            <li>Submit any content that is unlawful, harmful, threatening, abusive, harassing, defamatory, vulgar, obscene, or otherwise objectionable.</li>
            <li>Impersonate any person or entity.</li>
            <li>Engage in any activity that interferes with or disrupts the Service.</li>
            <li>Attempt to gain unauthorized access to any part of the Service.</li>
          </ul>

          {/* AdSense Banner */}
          <div className="my-8 flex justify-center">
            <div style={{ width: '100%', minHeight: '250px' }}>
              {/* Placeholder for a responsive AdSense ad unit */}
            </div>
          </div>

          <h2 className="text-2xl sm:text-3xl font-bold text-pink-300 pt-4 pb-2">4. Intellectual Property</h2>
          <p>The Service and its original content (excluding content provided by users), features, and functionality are and will remain the exclusive property of Telugu AI Voice Chat and its licensors. The Service is protected by copyright, trademark, and other laws of both India and foreign countries.</p>

          <h2 className="text-2xl sm:text-3xl font-bold text-pink-300 pt-4 pb-2">5. Third-Party Links & Advertisements</h2>
          <p>Our Service may contain links to third-party web sites or services that are not owned or controlled by us. We have no control over, and assume no responsibility for, the content, privacy policies, or practices of any third-party web sites or services. We also display advertisements from third parties, such as Google AdSense. Your interactions with these advertisements are governed by the advertiser's own terms and policies.</p>

          <h2 className="text-2xl sm:text-3xl font-bold text-pink-300 pt-4 pb-2">6. Limitation of Liability</h2>
          <p>In no event shall Telugu AI Voice Chat, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.</p>

          <h2 className="text-2xl sm:text-3xl font-bold text-pink-300 pt-4 pb-2">7. Governing Law</h2>
          <p>These Terms shall be governed and construed in accordance with the laws of India, without regard to its conflict of law provisions.</p>

          <h2 className="text-2xl sm:text-3xl font-bold text-pink-300 pt-4 pb-2">8. Changes</h2>
          <p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide notice of any changes by posting the new Terms on this page and updating the "Last Updated" date.</p>

          <h2 className="text-2xl sm:text-3xl font-bold text-pink-300 pt-4 pb-2">9. Contact Us</h2>
          <p>If you have any questions about these Terms, please contact us at: <a href="mailto:govardhanbommineni@gmail.com" className="blog-link" style={{ color: '#fff', fontWeight: 700 }}>govardhanbommineni@gmail.com</a></p>
        </div>
      </div>
    </div>
    </>
  );
};

export default TermsOfService;
